---
- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Copy MySQL configuration file
  copy:
    src: templates/my.cnf
    dest: /etc/mysql/my.cnf

- name: Start MySQL
  service:
    name: mysql
    state: started